server:
  port: 8001
  servlet:
    context-path: /devtools
spring:
  application:
    name: devTools
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devtools?characterEncoding=utf-8&serverTimezone=UTC
  file-storage:
    default-platform: minio-dev
    thumbnail-suffix: ".min.jpg" #缩略图后缀
    #对分布式文件存储OSS-MinIO进行配置
    minio:
      - platform: minio-dev # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: mxKVHfTCpGflGDxg
        secret-key: cMTKcEJATDNEPwS1kFSXB8Uw5WYszIbU
        end-point: http://192.168.125.245:9000
        bucket-name: yuxiang-dev
        # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        domain: http://192.168.125.245:9000/fntp
        # 基础路径
        base-path: devtools/
        file-size: 10485760000
        image-size: 1073741824
  servlet:
    multipart:
      max-request-size: 100000MB
      max-file-size: 100000MB
jwt:
  tokenHeader: Authorization
  secret: codewithme-secret-jwt
  salt: 999957
  expiration: 7
  tokenHead: 'Bear'
  sign: 'devTools'
